---
title: "Hands-Free Arm Wrestling"
---

Ever wanted to arm wrestle, but without actually having to arm wrestle? Look no further! 
Our project measures the electrical signals on your skin with an EMG sensor, and uses that to control a miniature arm wrestling game. 
When you (and a friend) flex, the electrical signals from your nerves that tell your muscles to contract get picked up by the 
sticky electrodes and sent into a circuit that amplifies them so that they are big enough to measure with the analog-to-digital
 converter on a STM32L432KC microcontroller.
 The microcontroller then sends the signals to the Upduino 3.1, a field-programmable gate array (FPGA). 
 The FPGA controls the LED matrix that displays the game.
  It has two modes, single and multiplayer. Selecting single player displays the raw signal as a bar chart. 
  Selecting multiplayer displays two competing bars, and updates the relative size of each depending on how hard you flex. 
  Getting your color to cover the entire screen means victory!

## New Hardware
- **EMG Sensors (x2)** - These sensors measure electrical activity on the skin and amplify it to an analog signal.
- **LED Matrix 32x16 (x1)** - This display has 512 RGB LEDs and is controllable from the FPGA.


## Specifications
For this project, the team will...
- [ ] Build a custom EMG sensor
- [ ] Write a device driver for ADC peripheral 
- [ ] Implement a SPI interface between MCU and FPGA
- [ ] Drive the LED matrix 
- [ ] Have single player and multiplayer modes
- [ ] Have game effects, e.g. loading screen and victory screens  

## Video 
{{< video  https://youtu.be/EtVBqZWrvIg >}}

## Acknowledgements
We would like to thank Prof Brake for teaching E155 this semester! We would also like to thank Jacob in the stockroom for helping us find all the parts we needed and our 
